name: Test Scheduled Job

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes (for testing)
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python script
        run: python python_main.py
